# Generated by Django 4.2 on 2023-05-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_id_threads_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='csv_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_path', models.CharField(default='', max_length=200)),
                ('message', models.TextField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.threads')),
            ],
        ),
    ]
