# Generated by Django 4.2 on 2023-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_changed_csv_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='threads',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
