# Generated by Django 4.2 on 2023-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_threads_slug_threads_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='changed_csv_path',
        ),
        migrations.AddField(
            model_name='threads',
            name='edited_csv_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
