# Generated by Django 4.2 on 2023-05-04 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='threads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
