# Generated by Django 4.2 on 2023-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_created_at_threads_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content_path',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
    ]
