# Generated by Django 4.2 on 2023-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_message_content_path_remove_message_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='content_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
