# Generated by Django 4.2 on 2023-05-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_message_content_message_content_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='threads',
            name='expl_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='explanation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.explanation'),
        ),
    ]
