# Generated by Django 4.2 on 2023-05-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_explanation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Explanation',
            new_name='Expl',
        ),
    ]
