# Generated by Django 4.2 on 2023-05-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_rename_explanation_expl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expl',
            new_name='Explanation',
        ),
    ]
