# Generated by Django 4.2 on 2023-08-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_threads_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='uuid',
            new_name='image_folder',
        ),
    ]
